### ISSUE TITLE
User can view top 100 cards of all available cards

### ISSUE THREAD

**Issue by Eric-Fried** [Eric-Fried/MTG-DeckBuilder#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can view top 100 cards of all available cards

## 📐 Functionality

user will see a list of the first 100 cards that exist within all cards avaialble, unless filter is selected

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/Eric-Fried/ajax-project/assets/146288203/efb3d1cd-c296-4c39-8d53-29e41d1c0e0b)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] write html for landing page
- [x] write css for landing page 
- [x] write html for search page 
- [x] write css for search page
- [x] write functionality for card search button 
  - [x] use querySelector to store card search button object
  - [x] add event listener to previously stored variable from previous step that listens for 'click' and when clicked view swaps to the card search database view
- [x] perform get request on mtg api and store as variable
- [x] pre populate page with cards aligned in rows
- [x] add event listener to home button that view swaps back to landing page when clicked 

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
