### ISSUE TITLE
User can filter cards by set

### ISSUE THREAD

**Issue by Eric-Fried** [Eric-Fried/MTG-DeckBuilder#2]
## ⚙️ Feature

User can filter cards by set

## 📐 Functionality

User will select from a drop down menu of sets available and then will only see the first 100 cards from that set unless color is also selected 
## 🖼️ Wireframes

![image](https://github.com/Eric-Fried/ajax-project/assets/146288203/b576d68d-077e-4b03-8e1d-10501b6b2c2a)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add event listener to the set dropdown menu that triggers whenever an option is selected
- [x] create getSetSortedCardData function that will use the same code as getCardData except in the api endpoint add "set=${event.target.value}
- [x] in event listener callback function call geSetSortedCardData:
  - [x] reuse code block from getCardData
  - [x] remove old card items from dom tree
  - [x] append new render results to dom tree

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
