### ISSUE TITLE
User can filter cards by color 

### ISSUE THREAD

**Issue by Eric-Fried** [Eric-Fried/MTG-DeckBuilder#3]
## ⚙️ Feature

User can filter cards by color 

## 📐 Functionality

User will select from a drop down of available colors and will then see a list of the first 100 cards of that color out of all available cards unless set is also selected in which case only the selected color and set will be shown 
## 🖼️ Wireframes
![image](https://github.com/Eric-Fried/ajax-project/assets/146288203/4e40afb5-2746-4ad5-8b8d-905bb2e0e265)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  add event listener to the color dropdown menu that triggers whenever an option is selected
- [x]  create getColorSortedCardData function that will use the same code as getCardData except in the api endpoint add "set=${event.target.value}
- [x] in event listener callback function call geColorSortedCardData:
   - [x]  reuse code block from getCardData
   - [x] remove old card items from dom tree
   - [x] append new render results to dom tree

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
