### ISSUE TITLE
User can add card to a deck

### ISSUE THREAD

**Issue by Eric-Fried** [Eric-Fried/MTG-DeckBuilder#4]
## ⚙️ Feature

User can add card to a deck

## 📐 Functionality

User will see a small "add" button in the top right of a card that is hovered over and if clicked it will add the card to a decklist 

## 🖼️ Wireframes

![image](https://github.com/Eric-Fried/ajax-project/assets/146288203/75e8b85a-a01a-4fc5-b31a-2d8ec434980e)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] create html for deck view and new deck button
- [x] Add a 'click' event listener to the deck builder button element that:
  - [x] view swaps to decks view which:
      - [x]  conditionally shows "no decks created yet" if data.editing is null
      - [ ] if data.editing is NOT null:
        - [ ] use render entry to pre populate the page with the images of the cards that have been added so far
- [x] add 'click' event listener to the new deck button element that:
  - [x]  stores a new deck object in data.decks array
  - [x] assigns an entryId property to the new object, taken from the nextEntryId property of the data model.
  - [x]  increments the nextEntryId property of the data model so that if another entry is submitted later, it will receive a different entryId.
  - [x]  adds the new object to the beginning of the data model's array of decks
- [x] Add a plus sign logo from font awesome that sits in the top right corner of each card image
- [x] Add a 'click" event listener to the plus sign logo that:
  - [x] adds the card that was  clicked on to the item in  data.editing
  - [x] reassign data.decks[i] to data.editing 
- [ ] In data.js, add a 'beforeunload' event listener to the window object that serializes the data model as JSON and stores the JSON in localStorage.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
